---
- name: Add ssv user
  ansible.builtin.user:
    name: "{{ ssv_user }}"
  register: ssv_user_meta

- name: Create data dir
  ansible.builtin.file:
    path: "{{ ssv_datadir }}"
    state: directory
    mode: "0750"
    owner: "{{ ssv_user }}"
    group: "{{ ssv_user }}"

- name: Set permissions
  ansible.builtin.command: "chown -R {{ ssv_user }}:{{ ssv_user }} {{ ssv_datadir }}" # noqa no-free-form
  changed_when: false

- name: Run ssv container
  community.docker.docker_container:
    name: "{{ ssv_container_name }}"
    image: "{{ ssv_container_image }}"
    state: started
    restart_policy: always
    stop_timeout: "{{ ssv_container_stop_timeout }}"
    ports: "{{ ssv_container_ports }}"
    volumes: "{{ ssv_container_volumes }}"
    env: "{{ ssv_container_env }}"
    command: "{{ ssv_container_command }}"
    networks: "{{ ssv_container_networks }}"
    user: "{{ ssv_user_meta.uid }}"
    pull: "{{ ssv_container_pull | bool }}"
    security_opts: "{{ ssv_container_security_opts }}"
